-- 003: grupos de personas y cargo.
--
-- Cada persona inicia sesión en la app con su usuario y clave y puede tener
-- su propia configuración. Para ordenarlas por equipo o zona hacen falta
-- grupos.
--
--   * iam.dmt_grupo (id, id_publico, nombre único, descripcion).
--   * iam.dmt_usuario_grupo (usuario_id, grupo_id), con borrado en cascada.
--   * iam.dmt_usuario suma cargo (opcional).
--   * La configuración de la app de cada persona va en
--     iam.dmt_usuario.atributos -> 'configApp'.
--
-- Para deshacer:
--   DROP TABLE IF EXISTS iam.dmt_usuario_grupo;
--   DROP TABLE IF EXISTS iam.dmt_grupo;
--   ALTER TABLE iam.dmt_usuario DROP COLUMN IF EXISTS cargo;

BEGIN;

CREATE TABLE IF NOT EXISTS iam.dmt_grupo (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_grupo PRIMARY KEY (id),
    CONSTRAINT uq_dmt_grupo_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_grupo_nombre UNIQUE (nombre)
);

COMMENT ON TABLE iam.dmt_grupo IS
    'Grupo de personas (por equipo o zona). Los miembros viven en iam.dmt_usuario_grupo.';
COMMENT ON COLUMN iam.dmt_grupo.id_publico IS
    'Identificador público del grupo (el que usa la API).';
COMMENT ON COLUMN iam.dmt_grupo.nombre IS
    'Nombre único del grupo, p. ej. Equipo Norte.';
COMMENT ON COLUMN iam.dmt_grupo.descripcion IS
    'Descripción libre del grupo (opcional).';

CREATE TABLE IF NOT EXISTS iam.dmt_usuario_grupo (
    usuario_id     BIGINT        NOT NULL,
    grupo_id       BIGINT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_usuario_grupo PRIMARY KEY (usuario_id, grupo_id),
    CONSTRAINT fk_dmt_usuario_grupo_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_dmt_usuario_grupo_grupo FOREIGN KEY (grupo_id)
        REFERENCES iam.dmt_grupo (id) ON DELETE CASCADE
);

COMMENT ON TABLE iam.dmt_usuario_grupo IS
    'Miembros de cada grupo. Al borrar un usuario o un grupo, sus filas se borran solas.';
COMMENT ON COLUMN iam.dmt_usuario_grupo.usuario_id IS
    'Persona miembro del grupo (iam.dmt_usuario.id).';
COMMENT ON COLUMN iam.dmt_usuario_grupo.grupo_id IS
    'Grupo al que pertenece la persona (iam.dmt_grupo.id).';

ALTER TABLE iam.dmt_usuario
  ADD COLUMN IF NOT EXISTS cargo text;

COMMENT ON COLUMN iam.dmt_usuario.cargo IS
    'Puesto de la persona en su equipo (opcional, texto libre).';

COMMIT;
