-- 005: cronograma de actividades. Lo que cada persona declara en la app
-- (visita, almuerzo, permisos, vacaciones, novedades).
--
-- La ubicación de registro solo se guarda si la jornada estaba iniciada al
-- cargar la actividad: cargada desde la casa no dice nada del lugar
-- declarado. `cliente_id` evita duplicados cuando la app reintenta.
BEGIN;

CREATE TABLE IF NOT EXISTS operations.dmt_actividad (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publico      UUID        NOT NULL DEFAULT system.uuidv7() UNIQUE,
    dispositivo_id  BIGINT      NOT NULL REFERENCES tracking.dmt_dispositivo(id),
    cliente_id      TEXT        NOT NULL,
    fecha           DATE        NOT NULL,
    hora            TEXT        NOT NULL CHECK (hora ~ '^[0-2][0-9]:[0-5][0-9]$'),
    tipo            TEXT        NOT NULL CHECK (tipo IN ('visita','almuerzo','permiso_medico','vacaciones','permiso','novedad')),
    lugar           TEXT,
    nota            TEXT,
    registrado_en   TIMESTAMPTZ NOT NULL,
    con_jornada     BOOLEAN     NOT NULL DEFAULT false,
    latitud         DOUBLE PRECISION,
    longitud        DOUBLE PRECISION,
    precision_m     REAL,
    eliminada       BOOLEAN     NOT NULL DEFAULT false,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (dispositivo_id, cliente_id)
);

CREATE INDEX IF NOT EXISTS dmt_actividad_fecha_idx ON operations.dmt_actividad (fecha, dispositivo_id) WHERE NOT eliminada;

GRANT SELECT, INSERT, UPDATE ON operations.dmt_actividad TO dmt;

COMMIT;
