-- 011: lista de clientes (lugares que se visitan) para registrar actividades
-- sin escribir la dirección cada vez. La ubicación sirve para comparar el
-- lugar declarado con donde estuvo el teléfono.
BEGIN;
CREATE TABLE IF NOT EXISTS operations.dmt_cliente (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                 TEXT NOT NULL,
    direccion              TEXT,
    latitud                DOUBLE PRECISION,
    longitud               DOUBLE PRECISION,
    activo                 BOOLEAN NOT NULL DEFAULT TRUE,
    creado_por_dispositivo BIGINT REFERENCES tracking.dmt_dispositivo(id) ON DELETE SET NULL,
    creado_en              TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_dmt_cliente_coordenadas CHECK ((latitud IS NULL) = (longitud IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_dmt_cliente_nombre ON operations.dmt_cliente (lower(nombre)) WHERE activo;
ALTER TABLE operations.dmt_actividad
    ADD COLUMN IF NOT EXISTS cliente_lugar_id BIGINT REFERENCES operations.dmt_cliente(id) ON DELETE SET NULL;
GRANT SELECT ON operations.dmt_cliente TO dmt_consulta;
COMMIT;
