-- 03_tracking.sql: equipos, posiciones y eventos.
--   * dmt_dispositivo.identificador es con lo que se identifica la app; no se
--     cambia. id_legado es el número anterior (la API todavía lo acepta).
--   * dmt_posicion.id admite insertar un valor explícito (después hay que
--     ajustar la secuencia con setval).
--   * dmt_posicion y dmt_evento están particionadas por mes según su hora
--     (registrado_en / ocurrido_en), con clave (id, hora) como pide PostgreSQL.
--     El receptor crea solo las particiones de los meses siguientes.

BEGIN;

-- ---------------------------------------------------------------------------
-- Dispositivos
-- ---------------------------------------------------------------------------
CREATE TABLE tracking.dmt_dispositivo (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico         UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado          BIGINT,
    nombre             TEXT        NOT NULL,
    identificador      TEXT        NOT NULL,
    habilitado         BOOLEAN     NOT NULL DEFAULT TRUE,
    estado             TEXT        NOT NULL DEFAULT 'DESCONOCIDO',
    ultima_conexion_en TIMESTAMPTZ,
    ultima_posicion_id BIGINT,
    grupo_id           BIGINT,
    telefono           TEXT,
    modelo             TEXT,
    contacto           TEXT,
    categoria          TEXT,
    atributos          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    expira_en          TIMESTAMPTZ,
    creado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_dispositivo PRIMARY KEY (id),
    CONSTRAINT uq_dmt_dispositivo_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_dispositivo_legado UNIQUE (id_legado)
);

COMMENT ON TABLE tracking.dmt_dispositivo IS
    'Dispositivo de seguimiento. atributos JSONB guarda la configuracion y el ultimo diagnostico.';
COMMENT ON COLUMN tracking.dmt_dispositivo.identificador IS
    'Identificador unico del dispositivo en la App. Contrato inmutable con la App.';
COMMENT ON COLUMN tracking.dmt_dispositivo.ultima_conexion_en IS
    'Ultima conexion conocida.';
COMMENT ON COLUMN tracking.dmt_dispositivo.ultima_posicion_id IS
    'Referencia informativa a tracking.dmt_posicion.id.';
COMMENT ON COLUMN tracking.dmt_dispositivo.atributos IS
    'Atributos variables: mobile.*, versiones, diagnostico, etc. Los campos de filtro/orden viven en columnas propias.';

-- ---------------------------------------------------------------------------
-- Posiciones (particionada por tiempo)
-- ---------------------------------------------------------------------------
CREATE TABLE tracking.dmt_posicion (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    dispositivo_id BIGINT      NOT NULL,
    protocolo      TEXT,
    latitud        DOUBLE PRECISION NOT NULL,
    longitud       DOUBLE PRECISION NOT NULL,
    altitud_m      DOUBLE PRECISION,
    velocidad_kmh  REAL,
    rumbo_grados   REAL,
    precision_m    REAL,
    bateria_pct    REAL,
    valida         BOOLEAN     NOT NULL DEFAULT TRUE,
    direccion      TEXT,
    red            TEXT,
    geocercas      TEXT,
    fijado_en      TIMESTAMPTZ,
    registrado_en  TIMESTAMPTZ NOT NULL,
    recibido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_posicion PRIMARY KEY (id, registrado_en),
    CONSTRAINT fk_dmt_posicion_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id)
) PARTITION BY RANGE (registrado_en);

COMMENT ON TABLE tracking.dmt_posicion IS
    'Historico de posiciones, particionado por mes de registrado_en. Fuente de replay.';
COMMENT ON COLUMN tracking.dmt_posicion.id IS
    'Id interno. GENERATED BY DEFAULT en el padre admite insercion explicita.';
COMMENT ON COLUMN tracking.dmt_posicion.velocidad_kmh IS
    'Velocidad en km/h (el protocolo OsmAnd envia nudos: speed * 1.852).';
COMMENT ON COLUMN tracking.dmt_posicion.rumbo_grados IS
    'Rumbo en grados (0-360).';
COMMENT ON COLUMN tracking.dmt_posicion.precision_m IS
    'Precision del fix, en metros.';
COMMENT ON COLUMN tracking.dmt_posicion.registrado_en IS
    'Hora del dispositivo/GPS (legado devicetime, UTC). Columna de particionado.';
COMMENT ON COLUMN tracking.dmt_posicion.recibido_en IS
    'Hora de recepcion en el servidor (legado servertime, UTC).';
COMMENT ON COLUMN tracking.dmt_posicion.fijado_en IS
    'Hora del fix GPS (legado fixtime, UTC); se conserva por fidelidad de replay.';
COMMENT ON COLUMN tracking.dmt_posicion.geocercas IS
    'Lista textual de ids de geocerca (legado geofenceids).';
COMMENT ON COLUMN tracking.dmt_posicion.atributos IS
    'Atributos variables del protocolo: batteryLevel, charge, motion, distance, totalDistance, etc.';

-- ---------------------------------------------------------------------------
-- Posicion actual (una fila por dispositivo, para el panel en vivo)
-- ---------------------------------------------------------------------------
CREATE TABLE tracking.dmt_posicion_actual (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    dispositivo_id BIGINT      NOT NULL,
    posicion_id    BIGINT,
    latitud        DOUBLE PRECISION NOT NULL,
    longitud       DOUBLE PRECISION NOT NULL,
    altitud_m      DOUBLE PRECISION,
    velocidad_kmh  REAL,
    rumbo_grados   REAL,
    precision_m    REAL,
    bateria_pct    REAL,
    valida         BOOLEAN     NOT NULL DEFAULT TRUE,
    fijado_en      TIMESTAMPTZ,
    registrado_en  TIMESTAMPTZ NOT NULL,
    recibido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_posicion_actual PRIMARY KEY (id),
    CONSTRAINT uq_dmt_posicion_actual_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_posicion_actual_dispositivo UNIQUE (dispositivo_id),
    CONSTRAINT fk_dmt_posicion_actual_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE CASCADE
);

COMMENT ON TABLE tracking.dmt_posicion_actual IS
    'Una fila por dispositivo con su ultima posicion. Evita MAX(registrado_en) sobre el historico en el panel en vivo.';

-- ---------------------------------------------------------------------------
-- Eventos (particionada por tiempo)
-- ---------------------------------------------------------------------------
CREATE TABLE tracking.dmt_evento (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    id_publico      UUID        NOT NULL DEFAULT system.uuidv7(),
    dispositivo_id  BIGINT,
    posicion_id     BIGINT,
    geocerca_id     BIGINT,
    mantenimiento_id BIGINT,
    tipo            TEXT        NOT NULL,
    ocurrido_en     TIMESTAMPTZ NOT NULL,
    recibido_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_evento PRIMARY KEY (id, ocurrido_en),
    CONSTRAINT fk_dmt_evento_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id)
) PARTITION BY RANGE (ocurrido_en);

COMMENT ON TABLE tracking.dmt_evento IS
    'Eventos de tracking: tipo, posicion y geocerca asociadas. Particionado por mes de ocurrido_en.';
COMMENT ON COLUMN tracking.dmt_evento.ocurrido_en IS
    'Hora del evento (legado eventtime, UTC). Columna de particionado.';
COMMENT ON COLUMN tracking.dmt_evento.atributos IS
    'Atributos variables del evento (JSON).';

-- ---------------------------------------------------------------------------
-- Particiones 2026-09 y 2026-10
-- ---------------------------------------------------------------------------
CREATE TABLE tracking.dmt_posicion_2026_09
    PARTITION OF tracking.dmt_posicion
    FOR VALUES FROM ('2026-09-01 00:00:00+00') TO ('2026-10-01 00:00:00+00');

CREATE TABLE tracking.dmt_posicion_2026_10
    PARTITION OF tracking.dmt_posicion
    FOR VALUES FROM ('2026-10-01 00:00:00+00') TO ('2026-11-01 00:00:00+00');

CREATE TABLE tracking.dmt_evento_2026_09
    PARTITION OF tracking.dmt_evento
    FOR VALUES FROM ('2026-09-01 00:00:00+00') TO ('2026-10-01 00:00:00+00');

CREATE TABLE tracking.dmt_evento_2026_10
    PARTITION OF tracking.dmt_evento
    FOR VALUES FROM ('2026-10-01 00:00:00+00') TO ('2026-11-01 00:00:00+00');

-- Si hiciera falta crear a mano la partición de un mes:
--
-- CREATE TABLE tracking.dmt_posicion_2026_11
--     PARTITION OF tracking.dmt_posicion
--     FOR VALUES FROM ('2026-11-01 00:00:00+00') TO ('2026-12-01 00:00:00+00');
-- CREATE TABLE tracking.dmt_evento_2026_11
--     PARTITION OF tracking.dmt_evento
--     FOR VALUES FROM ('2026-11-01 00:00:00+00') TO ('2026-12-01 00:00:00+00');

COMMIT;
