-- 06_audit.sql: registro de acciones (quién hizo qué y sobre qué).
-- Acción, entidad y hora tienen columna e índice; el detalle va en `datos`.

BEGIN;

CREATE TABLE audit.dmt_auditoria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    usuario_id     BIGINT,
    accion         TEXT        NOT NULL,
    entidad        TEXT,
    entidad_id     TEXT,
    descripcion    TEXT,
    datos          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    direccion      TEXT,
    agente         TEXT,
    ocurrido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_auditoria PRIMARY KEY (id),
    CONSTRAINT uq_dmt_auditoria_publico UNIQUE (id_publico),
    CONSTRAINT fk_dmt_auditoria_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE SET NULL
);

COMMENT ON TABLE audit.dmt_auditoria IS
    'Bitacora de acciones administrativas y de seguridad. Solo insercion desde la API.';
COMMENT ON COLUMN audit.dmt_auditoria.accion IS
    'Accion realizada: login, report, create, edit, remove, link, denied, logout...';
COMMENT ON COLUMN audit.dmt_auditoria.entidad IS
    'Objeto afectado: device, user, ...';
COMMENT ON COLUMN audit.dmt_auditoria.entidad_id IS
    'Id textual del objeto afectado.';
COMMENT ON COLUMN audit.dmt_auditoria.direccion IS
    'Direccion de origen en texto (no siempre es una IP valida).';
COMMENT ON COLUMN audit.dmt_auditoria.datos IS
    'Detalle variable de la accion (JSON).';

COMMIT;
