-- 07_system.sql: configuración y versión del esquema.
-- dmt_version_esquema anota qué archivos de base-de-datos/schema/ se aplicaron.

BEGIN;

-- ---------------------------------------------------------------------------
-- Configuracion
-- ---------------------------------------------------------------------------
CREATE TABLE system.dmt_configuracion (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    clave          TEXT        NOT NULL,
    valor          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    descripcion    TEXT,
    es_secreto     BOOLEAN     NOT NULL DEFAULT FALSE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_configuracion PRIMARY KEY (id),
    CONSTRAINT uq_dmt_configuracion_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_configuracion_clave UNIQUE (clave)
);

COMMENT ON TABLE system.dmt_configuracion IS
    'Parametros de la plataforma nueva. es_secreto=TRUE indica que el valor no debe exponerse por API ni en logs.';

-- ---------------------------------------------------------------------------
-- Version del esquema
-- ---------------------------------------------------------------------------
CREATE TABLE system.dmt_version_esquema (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    version        TEXT        NOT NULL,
    archivo        TEXT,
    checksum       TEXT,
    descripcion    TEXT,
    aplicado_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_version_esquema PRIMARY KEY (id),
    CONSTRAINT uq_dmt_version_esquema_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_version_esquema_version UNIQUE (version)
);

COMMENT ON TABLE system.dmt_version_esquema IS
    'Registro de aplicacion de los archivos database/schema/*.sql (version, archivo, sha256 opcional).';

COMMIT;
